# Generated by Django 5.0.8 on 2024-08-09 17:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="введите наименование",
                        max_length=100,
                        verbose_name="наименование",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        help_text="введите описание",
                        max_length=100,
                        verbose_name="описание",
                    ),
                ),
            ],
            options={
                "verbose_name": "Категория",
                "verbose_name_plural": "Категории",
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="введите наименование",
                        max_length=100,
                        verbose_name="наименование",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        help_text="введите описание",
                        max_length=100,
                        verbose_name="описание",
                    ),
                ),
                (
                    "photo",
                    models.ImageField(
                        blank=True,
                        help_text="загрузите фото продукта",
                        null=True,
                        upload_to="product/photo",
                        verbose_name="фото",
                    ),
                ),
                (
                    "price",
                    models.IntegerField(help_text="введите цену", verbose_name="цена"),
                ),
                (
                    "created_at",
                    models.DateField(
                        blank=True,
                        help_text="введите дату создания",
                        null=True,
                        verbose_name="дата создания",
                    ),
                ),
                (
                    "updated_at",
                    models.DateField(
                        blank=True,
                        help_text="введите дату последнего изменения",
                        null=True,
                        verbose_name="дата последнего изменения",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        help_text="введите категорию продукта",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="products",
                        to="catalog.category",
                        verbose_name="категория",
                    ),
                ),
            ],
            options={
                "verbose_name": "Продукт",
                "verbose_name_plural": "Продукты",
                "ordering": ["name", "category", "description"],
            },
        ),
    ]
