# Generated by Django 5.0.8 on 2024-08-22 07:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="views_counter",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Укажите количество просмотров",
                verbose_name="Счетчик просмотров",
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="description",
            field=models.TextField(
                help_text="Введите описание", max_length=100, verbose_name="Описание"
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="name",
            field=models.CharField(
                help_text="Введите наименование",
                max_length=100,
                verbose_name="Наименование",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="category",
            field=models.ForeignKey(
                blank=True,
                help_text="Введите категорию продукта",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="products",
                to="catalog.category",
                verbose_name="Категория",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="created_at",
            field=models.DateField(
                blank=True,
                help_text="Введите дату создания",
                null=True,
                verbose_name="Дата создания",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="description",
            field=models.TextField(
                help_text="Введите описание", max_length=100, verbose_name="Описание"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="name",
            field=models.CharField(
                help_text="Введите наименование",
                max_length=100,
                verbose_name="Наименование",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="photo",
            field=models.ImageField(
                blank=True,
                help_text="Загрузите фото продукта",
                null=True,
                upload_to="product/photo",
                verbose_name="Фото",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="price",
            field=models.IntegerField(help_text="Введите цену", verbose_name="Цена"),
        ),
        migrations.AlterField(
            model_name="product",
            name="updated_at",
            field=models.DateField(
                blank=True,
                help_text="Введите дату последнего изменения",
                null=True,
                verbose_name="Дата последнего изменения",
            ),
        ),
    ]
