# Generated by Django 5.0.8 on 2024-09-03 08:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0002_product_views_counter_alter_category_description_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Version",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "number_version",
                    models.IntegerField(
                        help_text="номер версии", verbose_name="номер версии"
                    ),
                ),
                (
                    "name_version",
                    models.CharField(
                        help_text="название версии",
                        max_length=50,
                        verbose_name="название версии",
                    ),
                ),
                (
                    "current_version",
                    models.BooleanField(verbose_name="признак текущей версии"),
                ),
                (
                    "product",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="catalog.product",
                        verbose_name="продукт",
                    ),
                ),
            ],
            options={
                "verbose_name": "Версия",
                "verbose_name_plural": "Версии",
            },
        ),
    ]
