# Generated by Django 5.0.8 on 2024-09-13 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0003_version"),
    ]

    operations = [
        migrations.AlterField(
            model_name="version",
            name="name_version",
            field=models.CharField(
                help_text="введите название версии",
                max_length=50,
                verbose_name="название версии",
            ),
        ),
        migrations.AlterField(
            model_name="version",
            name="number_version",
            field=models.IntegerField(
                help_text="введите номер версии", verbose_name="номер версии"
            ),
        ),
    ]
